import mongoose from "mongoose";

const UserResumeDetails=new mongoose.Schema({
    resumeId:{
        type:Object.mongoose.Schema.Types.resumeId,
        required:true
    },
    firstName:{
        type:String,
        required:true
    },
    lastName:{
        type:String,
        required:true
    },
    jobTitle:{
        type:String,
        required:true
    },
    address:{
        type:String,
        required:true
    },
    phone:{
        type:String,
        required:true
    },
    email:{
        type:String,
        required:true
    },
    github:{
        type:String,
        required:true
    },
    leetcode:{
        type:String,
        required:true
    },
    website:{
        type:String,
        required:true
    },
    themeColor:{
        type:String,
        default:"#ff6666",
    },
    summery:{
        type:String,
        required:true
    },
    skills:{
        type:[{
            skillName:{
                type:String,
                required:true
            },
            rating:{
                type:Number,
                required:true
            }
        }],
        required:true
    },
    experience:{
        type:[{
            companyName:{
                type:String,
                required:true
            },
            state:{
                type:String,
                required:true
            },
            position:{
                type:String,
                required:true
            },
            startDate:{
                type:Date,
                required:true
            },
            endDate:{
                type:Date,
                required:true
            },
            description:{
                type:String,
                required:true
            },
            currentlyWorking:{
                type:Boolean,
                required:true
            },
            workSummery:{
                type:String,
                required:true
            },
            city:{
                type:String,
                required:true
            }
        }],
        required:true
    },
    education:{
        type:[{
            schoolName:{
                type:String,
                required:true
            },
            degree:{
                type:String,
                required:true
            },
            startDate:{
                type:Date,
                required:true
            },
            endDate:{
                type:Date,
                required:true
            },
            description:{
                type:String,
                required:true
            },
            city:{
                type:String,
                required:true
            },
            state:{
                type:String,
                required:true
            },
            major:{
                type:String,
                required:true
            }
        }],
        required:true
    }
})